Changed call to unicode() to work with Python 3.
Python 3 no longer supports the unicode() function. I got this error when I tried the gv plugin:

    NameError: name 'unicode' is not defined

It seems that str() now does the job, so I selectively (i.e., when Python version is >= 3) changed calls to unicode() to str(). After I made the change, it worked with Python 3, I got my drawings. However, I have not tested it in Python 2 (but it should work).

More details here about the unicode() function here: https://stackoverflow.com/questions/36110598/nameerror-name-unicode-is-not-defined